CREATE TABLE NEWSY
(
    id bigint auto_increment PRIMARY KEY,
    TYTUL VARCHAR2,
    TRESC VARCHAR2,
    DATA date
);

CREATE TABLE TAGI
(
    NEWSY_ID int,
    TAG VARCHAR2 NOT NULL,
    FOREIGN KEY (NEWSY_ID) REFERENCES NEWSY ON DELETE CASCADE
)